// Deocamdată câteva exemple - lista mare o completăm separat
const wordPairs = [
  // === Cuvinte comune (100) ===
  ["pisică", "câine"],
  ["soare", "lună"],
  ["mare", "ocean"],
  ["carte", "revistă"],
  ["telefon", "tabletă"],
  ["masă", "birou"],
  ["scaun", "fotoliu"],
  ["mașină", "autobuz"],
  ["tren", "metrou"],
  ["avion", "elicopter"],
  ["pâine", "covrig"],
  ["lapte", "iaurt"],
  ["cafea", "ceai"],
  ["apă", "suc"],
  ["pahar", "cană"],
  ["creion", "pix"],
  ["hârtie", "caiet"],
  ["floare", "trandafir"],
  ["copac", "brad"],
  ["iarbă", "gazone"],
  ["pantof", "sandale"],
  ["tricou", "cămașă"],
  ["geacă", "pulover"],
  ["pantaloni", "blugi"],
  ["ceas", "brățară"],
  ["ușă", "fereastră"],
  ["cheie", "lacăt"],
  ["fruct", "măr"],
  ["banană", "portocală"],
  ["struguri", "pepene"],
  ["cireșe", "vișine"],
  ["cartof", "morcov"],
  ["roșie", "ardei"],
  ["salată", "varză"],
  ["pădure", "junglă"],
  ["desert", "prăjitură"],
  ["ciocolată", "vanilie"],
  ["gheață", "zăpadă"],
  ["foc", "flacără"],
  ["ploaie", "furtună"],
  ["vânt", "uragan"],
  ["nor", "ceață"],
  ["munte", "deal"],
  ["râu", "pârâu"],
  ["lac", "iaz"],
  ["pește", "ton"],
  ["pui", "rață"],
  ["vacă", "taur"],
  ["cal", "ponei"],
  ["oaie", "capră"],
  ["leu", "tigru"],
  ["urs", "panda"],
  ["cameră", "apartament"],
  ["casă", "vilă"],
  ["bloc", "turn"],
  ["oraș", "sat"],
  ["stradă", "bulevard"],
  ["pod", "tunel"],
  ["port", "gară"],
  ["școală", "liceu"],
  ["profesor", "învățător"],
  ["elev", "student"],
  ["carte", "manual"],
  ["film", "serial"],
  ["muzică", "concert"],
  ["teatru", "operă"],
  ["balet", "dans"],
  ["fotbal", "tenis"],
  ["baschet", "volei"],
  ["gimnastică", "yoga"],
  ["alergare", "maraton"],
  ["bicicletă", "trotinetă"],
  ["motor", "scooter"],
  ["benzină", "motorină"],
  ["electric", "hibrid"],
  ["computer", "laptop"],
  ["mouse", "touchpad"],
  ["tastatură", "controller"],
  ["internet", "wi-fi"],
  ["email", "chat"],
  ["facebook", "instagram"],
  ["whatsapp", "telegram"],
  ["google", "bing"],
  ["site", "blog"],
  ["server", "cloud"],
  ["program", "aplicație"],
  ["cod", "script"],
  ["robot", "android"],
  ["inteligență", "AI"],
  ["doctor", "asistent"],
  ["spital", "clinică"],
  ["farmacie", "medicament"],
  ["vaccin", "pastilă"],
  ["mașină", "camion"],
  ["bicicletă", "role"],
  ["cameră", "fotografie"],
  ["film", "cinema"],
  ["radio", "podcast"],

  // === Persoane celebre (100) ===
  ["Michael Jackson", "Elvis Presley"],
  ["Beyoncé", "Rihanna"],
  ["Britney Spears", "Christina Aguilera"],
  ["Taylor Swift", "Katy Perry"],
  ["Ed Sheeran", "Shawn Mendes"],
  ["Justin Bieber", "Harry Styles"],
  ["Adele", "Sam Smith"],
  ["Drake", "Kanye West"],
  ["Eminem", "50 Cent"],
  ["Snoop Dogg", "Ice Cube"],
  ["The Beatles", "The Rolling Stones"],
  ["Queen", "Pink Floyd"],
  ["Madonna", "Lady Gaga"],
  ["Shakira", "Jennifer Lopez"],
  ["Coldplay", "Imagine Dragons"],
  ["Linkin Park", "Green Day"],
  ["Metallica", "AC/DC"],
  ["Brad Pitt", "Leonardo DiCaprio"],
  ["Tom Cruise", "Keanu Reeves"],
  ["Johnny Depp", "Robert Downey Jr."],
  ["Scarlett Johansson", "Natalie Portman"],
  ["Emma Watson", "Emma Stone"],
  ["Angelina Jolie", "Megan Fox"],
  ["Chris Hemsworth", "Chris Evans"],
  ["Mark Ruffalo", "Jeremy Renner"],
  ["Tom Holland", "Andrew Garfield"],
  ["Zendaya", "Ariana Grande"],
  ["Selena Gomez", "Miley Cyrus"],
  ["Will Smith", "Denzel Washington"],
  ["Morgan Freeman", "Samuel L. Jackson"],
  ["Jackie Chan", "Jet Li"],
  ["Bruce Lee", "Chuck Norris"],
  ["Barack Obama", "Joe Biden"],
  ["Donald Trump", "George Bush"],
  ["Elon Musk", "Jeff Bezos"],
  ["Bill Gates", "Steve Jobs"],
  ["Mark Zuckerberg", "Larry Page"],
  ["Oprah Winfrey", "Ellen DeGeneres"],
  ["Kim Kardashian", "Kylie Jenner"],
  ["Kendall Jenner", "Gigi Hadid"],
  ["Cristiano Ronaldo", "Lionel Messi"],
  ["Neymar", "Kylian Mbappé"],
  ["Roger Federer", "Rafael Nadal"],
  ["Serena Williams", "Maria Sharapova"],
  ["LeBron James", "Michael Jordan"],
  ["Kobe Bryant", "Shaquille O’Neal"],
  ["Stephen Curry", "Kevin Durant"],
  ["Novak Djokovic", "Andy Murray"],
  ["Tiger Woods", "Phil Mickelson"],
  ["Usain Bolt", "Mo Farah"],
  ["Michael Phelps", "Ryan Lochte"],
  ["Simone Biles", "Nadia Comăneci"],
  ["Albert Einstein", "Isaac Newton"],
  ["Nikola Tesla", "Thomas Edison"],
  ["Stephen Hawking", "Carl Sagan"],
  ["Neil Armstrong", "Buzz Aldrin"],
  ["Galileo Galilei", "Copernic"],
  ["Platon", "Aristotel"],
  ["Shakespeare", "Charles Dickens"],
  ["J.K. Rowling", "George R.R. Martin"],
  ["Tolkien", "C.S. Lewis"],
  ["Stephen King", "Agatha Christie"],
  ["Stan Lee", "Jack Kirby"],
  ["Walt Disney", "Hayao Miyazaki"],
  ["Mickey Mouse", "Donald Duck"],
  ["Superman", "Batman"],
  ["Spider-Man", "Iron Man"],
  ["Thor", "Loki"],
  ["Hulk", "Thanos"],
  ["Wonder Woman", "Captain Marvel"],
  ["Joker", "Harley Quinn"],
  ["Mario", "Luigi"],
  ["Sonic", "Pikachu"],
  ["Ash Ketchum", "Misty"],
  ["Naruto", "Sasuke"],
  ["Goku", "Vegeta"],
  ["Luffy", "Zoro"],
  ["Darth Vader", "Luke Skywalker"],
  ["Yoda", "Obi-Wan"],
  ["Han Solo", "Chewbacca"],
  ["Frodo", "Sam"],
  ["Gandalf", "Saruman"],
  ["Aragorn", "Legolas"],
  ["Harry Potter", "Hermione"],
  ["Ron Weasley", "Draco Malfoy"],
  ["Voldemort", "Dumbledore"],
  ["Katniss Everdeen", "Peeta Mellark"],
  ["Neo", "Morpheus"],
  ["Trinity", "Agent Smith"],
  ["Rick", "Morty"],
  ["Homer Simpson", "Bart Simpson"],
  ["Peter Griffin", "Stewie Griffin"],
  ["SpongeBob", "Patrick"],
  ["Squidward", "Mr. Krabs"],
  ["Shrek", "Donkey"],
  ["Fiona", "Puss in Boots"],
  ["Elsa", "Anna"],
  ["Olaf", "Kristoff"],
  ["Woody", "Buzz Lightyear"],
  ["Simba", "Mufasa"],
  ["Scar", "Timon"],
  ["Pumba", "Rafiki"]
  ["Michael Jackson", "Elvis Presley"],
  ["Madonna", "Lady Gaga"],
  ["Britney Spears", "Christina Aguilera"],
  ["Beyoncé", "Rihanna"],
  ["Taylor Swift", "Katy Perry"],
  ["Ed Sheeran", "Shawn Mendes"],
  ["Justin Bieber", "Harry Styles"],
  ["Adele", "Sam Smith"],
  ["Drake", "Kanye West"],
  ["Eminem", "50 Cent"],
  ["Snoop Dogg", "Ice Cube"],
  ["Jay-Z", "Nas"],
  ["The Beatles", "The Rolling Stones"],
  ["Queen", "Pink Floyd"],
  ["Linkin Park", "Green Day"],
  ["Metallica", "AC/DC"],
  ["Coldplay", "Imagine Dragons"],
  ["Shakira", "Jennifer Lopez"],
  ["Cristiano Ronaldo", "Lionel Messi"],
  ["Neymar", "Kylian Mbappé"],
  ["Roger Federer", "Rafael Nadal"],
  ["Novak Djokovic", "Andy Murray"],
  ["LeBron James", "Michael Jordan"],
  ["Kobe Bryant", "Shaquille O’Neal"],
  ["Stephen Curry", "Kevin Durant"],
  ["Usain Bolt", "Mo Farah"],
  ["Michael Phelps", "Ryan Lochte"],
  ["Serena Williams", "Maria Sharapova"],
  ["Tiger Woods", "Phil Mickelson"],
  ["Brad Pitt", "Leonardo DiCaprio"],
  ["Tom Cruise", "Keanu Reeves"],
  ["Johnny Depp", "Robert Downey Jr."],
  ["Scarlett Johansson", "Natalie Portman"],
  ["Emma Watson", "Emma Stone"],
  ["Angelina Jolie", "Megan Fox"],
  ["Chris Hemsworth", "Chris Evans"],
  ["Tom Holland", "Andrew Garfield"],
  ["Zendaya", "Ariana Grande"],
  ["Selena Gomez", "Miley Cyrus"],
  ["Morgan Freeman", "Samuel L. Jackson"],
  ["Will Smith", "Denzel Washington"],
  ["Jackie Chan", "Jet Li"],
  ["Bruce Lee", "Chuck Norris"],
  ["Barack Obama", "Joe Biden"],
  ["Donald Trump", "George Bush"],
  ["Elon Musk", "Jeff Bezos"],
  ["Bill Gates", "Steve Jobs"],
  ["Mark Zuckerberg", "Larry Page"],
  ["Oprah Winfrey", "Ellen DeGeneres"],
  ["Kim Kardashian", "Kylie Jenner"],
  ["Kendall Jenner", "Gigi Hadid"],
  ["Stan Lee", "Jack Kirby"],
  ["Walt Disney", "Hayao Miyazaki"],
  ["Superman", "Batman"],
  ["Spider-Man", "Iron Man"],
  ["Thor", "Loki"],
  ["Hulk", "Thanos"],
  ["Wonder Woman", "Captain Marvel"],
  ["Joker", "Harley Quinn"],
  ["Mario", "Luigi"],
  ["Sonic", "Pikachu"],
  ["Naruto", "Sasuke"],
  ["Goku", "Vegeta"],
  ["Luffy", "Zoro"],
  ["Darth Vader", "Luke Skywalker"],
  ["Yoda", "Obi-Wan"],
  ["Han Solo", "Chewbacca"],
  ["Frodo", "Sam"],
  ["Gandalf", "Saruman"],
  ["Aragorn", "Legolas"],
  ["Harry Potter", "Hermione"],
  ["Ron Weasley", "Draco Malfoy"],
  ["Voldemort", "Dumbledore"],
  ["Katniss Everdeen", "Peeta Mellark"],
  ["Neo", "Morpheus"],
  ["Rick", "Morty"],
  ["Homer Simpson", "Bart Simpson"],
  ["Peter Griffin", "Stewie Griffin"],
  ["SpongeBob", "Patrick"],
  ["Shrek", "Donkey"],
  ["Elsa", "Anna"],
  ["Woody", "Buzz Lightyear"],
  ["Simba", "Mufasa"],
  ["Scar", "Timon"],
  ["Olaf", "Kristoff"],
  ["Tony Stark", "Captain America"],
  ["Doctor Strange", "Wong"],
  ["Black Panther", "Shuri"],
  ["Deadpool", "Cable"],
  ["Wolverine", "Professor X"],
  ["Magneto", "Mystique"],
  ["Hulk Hogan", "The Rock"],
  ["John Cena", "Undertaker"],

  // === Personalități românești (100) ===
  ["Gheorghe Hagi", "Adrian Mutu"],
  ["Cristian Chivu", "Ilie Năstase"],
  ["Simona Halep", "Nadia Comăneci"],
  ["Helmut Duckadam", "Florin Prunea"],
  ["Florin Piersic", "Ștefan Bănică Sr."],
  ["Ștefan Bănică Jr.", "Smiley"],
  ["Delia", "Andra"],
  ["Inna", "Alexandra Stan"],
  ["Irina Rimes", "The Motans"],
  ["Carla’s Dreams", "Guess Who"],
  ["Puya", "BUG Mafia"],
  ["Paraziții", "La Familia"],
  ["Mihai Eminescu", "Ion Creangă"],
  ["Mircea Eliade", "Emil Cioran"],
  ["Lucian Blaga", "Tudor Arghezi"],
  ["Nicolae Ceaușescu", "Elena Ceaușescu"],
  ["Ion Iliescu", "Traian Băsescu"],
  ["Klaus Iohannis", "Marcel Ciolacu"],
  ["George Simion", "Diana Șoșoacă"],
  ["Mihai Viteazul", "Ștefan cel Mare"],
  ["Alexandru Ioan Cuza", "Carol I"],
  ["Regele Mihai", "Regina Maria"],
  ["Avram Iancu", "Iancu de Hunedoara"],
  ["Nicolae Iorga", "Titu Maiorescu"],
  ["Grigore Antipa", "Victor Babeș"],
  ["Henri Coandă", "Aurel Vlaicu"],
  ["Gheorghe Zamfir", "Ion Voicu"],
  ["Marin Moraru", "Toma Caragiu"],
  ["Amza Pellea", "Jean Constantin"],
  ["Dem Rădulescu", "Stela Popescu"],
  ["Alexandru Arșinel", "Tamara Buciuceanu"],
  ["Horațiu Mălăele", "Marcel Iureș"],
  ["Victor Rebengiuc", "Maia Morgenstern"],
  ["Florin Călinescu", "Mugur Mihăescu"],
  ["Dan Negru", "Andreea Esca"],
  ["Andi Moisescu", "Cătălin Măruță"],
  ["Mihai Bendeac", "Cheloo"],
  ["Marius Moga", "Connect-R"],
  ["Loredana Groza", "Paula Seling"],
  ["Horia Brenciu", "Ștefan Bănică Jr."],
  ["Corina Chiriac", "Mirabela Dauer"],
  ["Angela Similea", "Marina Voica"],
  ["Gică Petrescu", "Dan Spătaru"],
  ["Irina Loghin", "Maria Tănase"],
  ["Liviu Vârciu", "Dorian Popa"],
  ["Speak", "Alex Velea"],
  ["Răzvan și Dani", "Cătălin Bordea"],
  ["Mihai Trăistariu", "O-Zone"],
  ["3 Sud Est", "Voltaj"],
  ["Holograf", "Compact"],
  ["Cargo", "Iris"],
  ["Șuie Paparude", "Subcarpați"],
  ["Guess Who", "DOC"],
  ["Spike", "Maximilian"],
  ["Rubik’s Cube", "Mihai Bobonete"],
  ["Cosmin Nedelcu (Micutzu)", "Dan Badea"],
  ["Costel Bojog", "Teo"],
  ["Radu Beligan", "Ion Caramitru"],
  ["Adrian Păunescu", "Octavian Paler"],
  ["Mircea Badea", "Victor Ciutacu"],
  ["Cristian Tudor Popescu", "Moise Guran"],
  ["Andreea Marin", "Teo Trandafir"],
  ["Gabriela Firea", "Elena Udrea"],
  ["Victor Ponta", "Dacian Cioloș"],
  ["Raed Arafat", "Adrian Streinu-Cercel"],
  ["Carmen Harra", "Irina Margareta Nistor"],
  ["Tudor Chirilă", "Dan Teodorescu"],
  ["Ștefan Răzvan", "Adi Despot"],
  ["CRBL", "Cheloo"],
  ["Florin Salam", "Nicolae Guță"],
  ["Adrian Minune", "Tzancă Uraganu"],
  ["Jador", "Vali Vijelie"],
  ["Jean de la Craiova", "Nicolae Furdui Iancu"],
  ["Maria Dragomiroiu", "Sofia Vicoveanca"],
  ["Fuego", "Ștefan Hrușcă"],
  ["Mădălina Manole", "Laura Stoica"],
  ["Corina Bud", "Anda Adam"],
  ["Jo", "Antonia"],
  ["Alina Eremia", "Lidia Buble"],
  ["Raluka", "DJ Project"],
  ["Killa Fonic", "Deliric"],
  ["Guess Who", "Bitză"],
  ["Paraziții", "BUG Mafia"],
  ["Spike", "Connect-R"],
  ["Carla’s Dreams", "Smiley"],
  ["Delia", "Andra"],
  ["Irina Rimes", "Nicole Cherry"],
  ["Dorian Popa", "Speak"],
  ["Inna", "Alexandra Stan"],
  ["Amna", "Ruby"],
  ["Puya", "La Familia"],
  ["Voltaj", "3 Sud Est"],
  ["Holograf", "Cargo"],
  ["Iris", "Compact"],
  ["Ștefan Bănică Jr.", "Horia Brenciu"]
];
  
